In [1]:
import array

In [2]:
# creating

arr1 = array.array('i',[10,20,30,40,50])
print(arr1)

array('i', [10, 20, 30, 40, 50])


# Accessing (Indexing)

In [3]:
arr1[3]

40

In [4]:
arr1[0]

10

In [11]:
arr1[4]

50

# Traversal

In [13]:
for num in arr1:
    print(num,end=" ")

10 20 30 40 50 

# Insertion

In [14]:
arr1.insert(3,35)
arr1

array('i', [10, 20, 30, 35, 40, 50])

# Deletion

In [15]:
arr1.remove(30)  # Only removes first occurence 
arr1

array('i', [10, 20, 35, 40, 50])

# Updation

In [16]:
arr1[2] = 30
arr1

array('i', [10, 20, 30, 40, 50])

# Sorting

In [17]:
arr2 = array.array('i',[70,60,80])
arr2

array('i', [60, 70, 80])

In [18]:
array.array('i',sorted(arr2))

array('i', [60, 70, 80])

# Merging

In [19]:
arr1

array('i', [10, 20, 30, 40, 50])

In [20]:
arr2

array('i', [60, 70, 80])

In [22]:
arr3 = arr1 + arr2
arr3

array('i', [10, 20, 30, 40, 50, 60, 70, 80])

# Splitting

In [24]:
indx = int(len(arr3)/2)

In [26]:
arr3[:indx]

array('i', [10, 20, 30, 40])

In [27]:
arr3[indx:]

array('i', [50, 60, 70, 80])

-- ---------------------------------------------------------------
# NUMPY
-------------------------------------------------------------------------------------------------------------------------------------------------------

In [1]:
import numpy as np

In [2]:
np1 = np.array([10,20,30,40,50])
np2 = np.array([50,60,70])

In [3]:
# access
np1[3]

np.int64(40)

In [5]:
# traversal
for item in np1:
    print(item,end=" ")

10 20 30 40 50 

In [6]:
# insertion
np.insert(np1,3,35)

array([10, 20, 30, 35, 40, 50])

In [7]:
np.delete(np1,3)

array([10, 20, 30, 50])

In [8]:
# updation
np1[2] = 69
np1

array([10, 20, 69, 40, 50])

In [9]:
# sorting
np3 = np.array([5,3,7,6,2,9])
np.sort(np3)

array([2, 3, 5, 6, 7, 9])

In [11]:
np3
# that means it return copy not view

array([5, 3, 7, 6, 2, 9])

In [14]:
np.concatenate((np1,np2))

array([10, 20, 69, 40, 50, 50, 60, 70])

In [16]:
# splitting
split1, split2 = np.array_split(np3,2)

In [17]:
split1

array([5, 3, 7])

In [18]:
split2

array([6, 2, 9])